import HeaderComponent from "@/components/header/Header"
import SidebarComponent from "@/components/sidebar/Sidebar"

export const metadata = {
  title: 'Timesheet',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <HeaderComponent />
          <SidebarComponent />
          <div className="absolute top-[70px] left-[300px] mt-[30px] mx-[15px] mb-0 w-[calc(100%-330px)]">
            {children}
          </div>
    </div>
  )
}